# \u6570\u636E\u5E93\u914D\u7F6E\uFF0C\u53EF\u4EE5\u53C2\u8003  DataSourceProperties \u7C7B
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTImezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: alymysql123456



mybatis:
  mapper-locations: classpath:mapper/*.xml
